trigger:
- main

strategy:
  matrix:
    windows-msvc-dist:
      imageName: 'windows-2022'
      config: 'MinSizeRel'
      cc: 'cl'
      cxx: 'cl'
    windows-msvc-release:
      imageName: 'windows-2022'
      config: 'RelWithDebInfo'
      cc: 'cl'
      cxx: 'cl'
    windows-msvc-debug:
      imageName: 'windows-2022'
      config: 'Debug'
      cc: 'cl'
      cxx: 'cl'
    windows-clang-dist:
      imageName: 'windows-2022'
      config: 'MinSizeRel'
      cc: 'clang'
      cxx: 'clang'
    windows-clang-release:
      imageName: 'windows-2022'
      config: 'RelWithDebInfo'
      cc: 'clang'
      cxx: 'clang'
    windows-clang-debug:
      imageName: 'windows-2022'
      config: 'Debug'
      cc: 'clang'
      cxx: 'clang'
    macos-dist:
      imageName: 'macos-latest'
      config: 'MinSizeRel'
      cc: 'clang'
      cxx: 'clang++'
    macos-release:
      imageName: 'macos-latest'
      config: 'RelWithDebInfo'
      cc: 'clang'
      cxx: 'clang++'
    macos-debug:
      imageName: 'macos-latest'
      config: 'Debug'
      cc: 'clang'
      cxx: 'clang++'
    linux-dist:
      imageName: 'ubuntu-latest'
      config: 'MinSizeRel'
      cc: 'clang'
      cxx: 'clang++'
    linux-release:
      imageName: 'ubuntu-latest'
      config: 'RelWithDebInfo'
      cc: 'clang'
      cxx: 'clang++'
    linux-debug:
      imageName: 'ubuntu-latest'
      config: 'Debug'
      cc: 'clang'
      cxx: 'clang++'

variables:
  artifactArchive: $(Build.ArtifactStagingDirectory)/purpl-$(imageName)-$(config)-$(cc).7z
  vulkanSdkVersion: 1.3.211
  vulkanSdk: C:\VulkanSDK\$(vulkanSdkVersion).0

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: true

  - script: |
      call tools\installvulkan.bat
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Install Vulkan SDK

  - bash: |
      chmod a+x tools/fixperms.sh
      tools/fixperms.sh
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
    displayName: Set executable bit on tools

  - bash: |
      curl -fsGL https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      curl -fsGL https://packages.lunarg.com/vulkan/$(vulkanSdkVersion)/lunarg-vulkan-$(vulkanSdkVersion)-focal.list | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-focal.list
      sudo apt update -qq
      sudo apt install -y libsdl2-dev vulkan-sdk
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Install SDL and Vulkan SDK with APT

  - bash: |
      brew install sdl2
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Install SDL with Homebrew

  - script: |
      pip install MarkupSafe==2.1.0
      pip install Jinja2==3.0.3
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Install requirements for glad

  - script: |
      curl -fsGL https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/windows/continuous_release_2017/384/20220202-124410/install.zip -o glslc.zip
      7z x glslc.zip
      mv install glslc
      curl -fsGL https://github.com/KhronosGroup/SPIRV-Cross/releases/download/2021-01-15/spirv-cross-vs2017-64bit-9acb9ec31f.tar.gz -o spirv-cross.tar.gz
      mkdir spirv-cross
      tar xvzf spirv-cross.tar.gz -C spirv-cross
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Install shader compilation tools (Windows)

  - script: |
      curl -fsGL https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/380/20220202-124409/install.tgz -o glslc.tar.gz
      tar xvzf glslc.tar.gz
      mv install glslc
      curl -fsGL https://github.com/KhronosGroup/SPIRV-Cross/releases/download/2021-01-15/spirv-cross-clang-trusty-64bit-9acb9ec31f.tar.gz -o spirv-cross.tar.gz
      mkdir spirv-cross
      tar xvzf spirv-cross.tar.gz -C spirv-cross
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Install shader compilation tools (Linux)

  - script: |
      curl -fsGL https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/macos/continuous_clang_release/388/20220202-124410/install.tgz -o glslc.tar.gz
      tar xvzf glslc.tar.gz
      mv install glslc
      curl -fsGL https://github.com/KhronosGroup/SPIRV-Cross/releases/download/2021-01-15/spirv-cross-clang-macos-64bit-9acb9ec31f.tar.gz -o spirv-cross.tar.gz
      mkdir spirv-cross
      tar xvzf spirv-cross.tar.gz -C spirv-cross
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Install shader compilation tools (macOS)

  - script: |
      call tools\buildenv.bat x64
      cmake -S. -Bbuild -GNinja -DVULKAN_SDK=$(vulkanSdk) -DVulkan_LIBRARY=$(vulkanSdk)/Lib/vulkan-1.lib -DVulkan_INCLUDE_DIR=$(vulkanSdk)/Include -DCMAKE_C_COMPILER=$(cc) -DCMAKE_CXX_COMPILER=$(cxx) -DCMAKE_BUILD_TYPE=$(config) -DPURPL_ENABLE_DISCORD=0 -DPURPL_ENABLE_STEAM=0
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    env:
      PATH: 'glslc/bin;spirv-cross/bin;$(PATH)'
    displayName: Generate build files (Windows)

  - script: |
      cmake -S. -Bbuild -GNinja -DVulkan_LIBRARY=/usr/lib/x86_64-linux-gnu/libvulkan.so -DCMAKE_C_COMPILER=$(cc) -DCMAKE_CXX_COMPILER=$(cxx) -DCMAKE_BUILD_TYPE=$(config) -DSDL_LIBRARY=/usr/lib/x86_64-linux-gnu/libSDL2.so -DPURPL_USE_SYSTEM_SDL=1 -DPURPL_ENABLE_DISCORD=0 -DPURPL_ENABLE_STEAM=0
    condition: eq(variables['Agent.OS'], 'Linux')
    env:
      PATH: 'glslc/bin:spirv-cross/bin:$(PATH)'
    displayName: Generate build files (Linux)

  - script: |
      cmake -S. -Bbuild -GXcode -DCMAKE_C_COMPILER=$(cc) -DCMAKE_CXX_COMPILER=$(cxx) -DCMAKE_BUILD_TYPE=$(config) -DPURPL_USE_SYSTEM_SDL=1 -DPURPL_ENABLE_DISCORD=0 -DPURPL_ENABLE_STEAM=0
    condition: eq(variables['Agent.OS'], 'Darwin')
    env:
      PATH: 'glslc/bin:spirv-cross/bin:$(PATH)'
    displayName: Generate build files (macOS)

  - script: |
      call tools\buildenv.bat x64
      cmake --build build --config $(config)
      cmake --install build --config $(config)
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Build (Windows)

  - script: |
      cmake --build build --config $(config)
      cmake --install build --config $(config)
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
    displayName: Build (non-Windows)

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: build/install
      archiveFile: $(artifactArchive)
      includeRootFolder: true
      archiveType: 7z
      replaceExistingArchive: true
      verbose: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(artifactArchive)
      artifactName: $(imageName)-$(config)-$(cc)

