// Functions and definitions related to errors
//
// Copyright 2022 MobSlicer152
// This file is part of Purpl Engine
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "purpl/util/error.h"

#include <stb_sprintf.h>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

static u32 win32_errno_map[] = {
	// Directly stolen from
	// https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/errno.cc
	ERROR_ACCESS_DENIED,
	EACCES,
	ERROR_ACTIVE_CONNECTIONS,
	EAGAIN,
	ERROR_ALREADY_EXISTS,
	EEXIST,
	ERROR_BAD_DEVICE,
	ENODEV,
	ERROR_BAD_EXE_FORMAT,
	ENOEXEC,
	ERROR_BAD_NETPATH,
	ENOENT,
	ERROR_BAD_NET_NAME,
	ENOENT,
	ERROR_BAD_NET_RESP,
	ENOSYS,
	ERROR_BAD_PATHNAME,
	ENOENT,
	ERROR_BAD_PIPE,
	EINVAL,
	ERROR_BAD_UNIT,
	ENODEV,
	ERROR_BAD_USERNAME,
	EINVAL,
	ERROR_BEGINNING_OF_MEDIA,
	EIO,
	ERROR_BROKEN_PIPE,
	EPIPE,
	ERROR_BUSY,
	EBUSY,
	ERROR_BUS_RESET,
	EIO,
	ERROR_CALL_NOT_IMPLEMENTED,
	ENOSYS,
	ERROR_CANCELLED,
	EINTR,
	ERROR_CANNOT_MAKE,
	EPERM,
	ERROR_CHILD_NOT_COMPLETE,
	EBUSY,
	ERROR_COMMITMENT_LIMIT,
	EAGAIN,
	ERROR_CONNECTION_REFUSED,
	ECONNREFUSED,
	ERROR_CRC,
	EIO,
	ERROR_DEVICE_DOOR_OPEN,
	EIO,
	ERROR_DEVICE_IN_USE,
	EAGAIN,
	ERROR_DEVICE_REQUIRES_CLEANING,
	EIO,
	ERROR_DEV_NOT_EXIST,
	ENOENT,
	ERROR_DIRECTORY,
	ENOTDIR,
	ERROR_DIR_NOT_EMPTY,
	ENOTEMPTY,
	ERROR_DISK_CORRUPT,
	EIO,
	ERROR_DISK_FULL,
	ENOSPC,
	ERROR_DS_GENERIC_ERROR,
	EIO,
	ERROR_DUP_NAME,
	EEXIST,
	ERROR_EAS_DIDNT_FIT,
	ENOSPC,
	ERROR_EAS_NOT_SUPPORTED,
	ENOTSUP,
	ERROR_EA_LIST_INCONSISTENT,
	EINVAL,
	ERROR_EA_TABLE_FULL,
	ENOSPC,
	ERROR_END_OF_MEDIA,
	ENOSPC,
	ERROR_EOM_OVERFLOW,
	EIO,
	ERROR_EXE_MACHINE_TYPE_MISMATCH,
	ENOEXEC,
	ERROR_EXE_MARKED_INVALID,
	ENOEXEC,
	ERROR_FILEMARK_DETECTED,
	EIO,
	ERROR_FILENAME_EXCED_RANGE,
	ENAMETOOLONG,
	ERROR_FILE_CORRUPT,
	EEXIST,
	ERROR_FILE_EXISTS,
	EEXIST,
	ERROR_FILE_INVALID,
	ENXIO,
	ERROR_FILE_NOT_FOUND,
	ENOENT,
	ERROR_HANDLE_DISK_FULL,
	ENOSPC,
	ERROR_HANDLE_EOF,
	ENODATA,
	ERROR_INVALID_ADDRESS,
	EINVAL,
	ERROR_INVALID_AT_INTERRUPT_TIME,
	EINTR,
	ERROR_INVALID_BLOCK_LENGTH,
	EIO,
	ERROR_INVALID_DATA,
	EINVAL,
	ERROR_INVALID_DRIVE,
	ENODEV,
	ERROR_INVALID_EA_NAME,
	EINVAL,
	ERROR_INVALID_EXE_SIGNATURE,
	ENOEXEC,
	ERROR_INVALID_FUNCTION,
	EINVAL,
	ERROR_INVALID_HANDLE,
	EBADF,
	ERROR_INVALID_NAME,
	ENOENT,
	ERROR_INVALID_PARAMETER,
	EINVAL,
	ERROR_INVALID_SIGNAL_NUMBER,
	EINVAL,
	ERROR_IOPL_NOT_ENABLED,
	ENOEXEC,
	ERROR_IO_DEVICE,
	EIO,
	ERROR_IO_INCOMPLETE,
	EAGAIN,
	ERROR_IO_PENDING,
	EAGAIN,
	ERROR_LOCK_VIOLATION,
	EBUSY,
	ERROR_MAX_THRDS_REACHED,
	EAGAIN,
	ERROR_META_EXPANSION_TOO_LONG,
	EINVAL,
	ERROR_MOD_NOT_FOUND,
	ENOENT,
	ERROR_MORE_DATA,
	EMSGSIZE,
	ERROR_NEGATIVE_SEEK,
	EINVAL,
	ERROR_NETNAME_DELETED,
	ENOENT,
	ERROR_NOACCESS,
	EFAULT,
	ERROR_NONE_MAPPED,
	EINVAL,
	ERROR_NONPAGED_SYSTEM_RESOURCES,
	EAGAIN,
	ERROR_NOT_CONNECTED,
	ENOLINK,
	ERROR_NOT_ENOUGH_MEMORY,
	ENOMEM,
	ERROR_NOT_ENOUGH_QUOTA,
	EIO,
	ERROR_NOT_OWNER,
	EPERM,
	ERROR_NOT_READY,
	EIO,
	ERROR_NOT_SAME_DEVICE,
	EXDEV,
	ERROR_NOT_SUPPORTED,
	ENOSYS,
	ERROR_NO_DATA,
	EPIPE,
	ERROR_NO_DATA_DETECTED,
	EIO,
	ERROR_NO_MEDIA_IN_DRIVE,
	EIO,
	ERROR_NO_MORE_FILES,
	ENFILE,
	ERROR_NO_MORE_ITEMS,
	ENFILE,
	ERROR_NO_MORE_SEARCH_HANDLES,
	ENFILE,
	ERROR_NO_PROC_SLOTS,
	EAGAIN,
	ERROR_NO_SIGNAL_SENT,
	EIO,
	ERROR_NO_SYSTEM_RESOURCES,
	EFBIG,
	ERROR_NO_TOKEN,
	EINVAL,
	ERROR_OPEN_FAILED,
	EIO,
	ERROR_OPEN_FILES,
	EAGAIN,
	ERROR_OUTOFMEMORY,
	ENOMEM,
	ERROR_PAGED_SYSTEM_RESOURCES,
	EAGAIN,
	ERROR_PAGEFILE_QUOTA,
	EAGAIN,
	ERROR_PATH_NOT_FOUND,
	ENOENT,
	ERROR_PIPE_BUSY,
	EBUSY,
	ERROR_PIPE_CONNECTED,
	EBUSY,
	ERROR_PIPE_LISTENING,
	EAGAIN,
	ERROR_PIPE_NOT_CONNECTED,
	EIO,
	ERROR_POSSIBLE_DEADLOCK,
	EDEADLOCK,
	ERROR_PRIVILEGE_NOT_HELD,
	EPERM,
	ERROR_PROCESS_ABORTED,
	EFAULT,
	ERROR_PROC_NOT_FOUND,
	ESRCH,
	ERROR_REM_NOT_LIST,
	EINVAL,
	ERROR_SECTOR_NOT_FOUND,
	EINVAL,
	ERROR_SEEK,
	EINVAL,
	ERROR_SERVICE_REQUEST_TIMEOUT,
	EBUSY,
	ERROR_SETMARK_DETECTED,
	EIO,
	ERROR_SHARING_BUFFER_EXCEEDED,
	ENOLCK,
	ERROR_SHARING_VIOLATION,
	EBUSY,
	ERROR_SIGNAL_PENDING,
	EBUSY,
	ERROR_SIGNAL_REFUSED,
	EIO,
	ERROR_SXS_CANT_GEN_ACTCTX,
	EIO,
	ERROR_THREAD_1_INACTIVE,
	EINVAL,
	ERROR_TIMEOUT,
	EBUSY,
	ERROR_TOO_MANY_LINKS,
	EMLINK,
	ERROR_TOO_MANY_OPEN_FILES,
	EMFILE,
	ERROR_UNEXP_NET_ERR,
	EIO,
	ERROR_WAIT_NO_CHILDREN,
	ECHILD,
	ERROR_WORKING_SET_QUOTA,
	EAGAIN,
	ERROR_WRITE_PROTECT,
	EROFS
};

PURPL_API u32 purpl_win32_error_to_errno(u32 error)
{
	size_t i;

	for (i = 0; i < PURPL_SIZEOF_ARRAY(win32_errno_map) / 2; i += 2) {
		if (win32_errno_map[i] == error)
			return win32_errno_map[i];
	}

	return 0;
}

PURPL_API u32 purpl_errno_to_win32_error(u32 error)
{
	size_t i;

	for (i = 1; i < PURPL_SIZEOF_ARRAY(win32_errno_map) / 2; i += 2) {
		if (win32_errno_map[i] == error)
			return win32_errno_map[i];
	}

	return 0;
}
#endif // _WIN32

PURPL_API const char *purpl_strerror(void)
{
	static char buf[PURPL_STATIC_BUF_MAX];

	stbsp_snprintf(buf, PURPL_STATIC_BUF_MAX, "%s (errno %d)",
		       strerror(errno), errno);

	return buf;
}
