name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build dependencies
        run: python tools\deps.py --verbose

      - name: Generate build files
        run: tools\gn gen out\win

      - name: Build
        run: tools\ninja -C out\win

      - name: Add artifacts to folder
        run: |
          mkdir build
          xcopy /y out\win\engine.dll build
          xcopy /y out\win\main.exe build
          xcopy /y deps\win-x64\bin\* build
          xcopy /i/y deps\licenses build\licenses
          copy LICENSE build\licenses\purpl.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: build

      - name: Create zip of artifacts for release
        run: |
          "$Env:PROGRAMFILES\7-Zip\7z.exe a -tzip build-windows.zip build\*"

      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-windows.zip

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set permissions on executables
        run: |
          chmod a+x tools/deps.py
          chmod a+x tools/gn
          chmod a+x tools/ninja

      - name: Build dependencies
        run: tools/deps.py --verbose
        
      - name: Generate build files
        run: tools/gn gen out/mac
        
      - name: Build
        run: tools/ninja -C out/mac -j$[`nproc` + 2]

      - name: Add artifacts to folder
        run: |
          mkdir build
          printf '#!/usr/bin/env bash\n\nchmod a+x main\nexportHERE="$(dirname "$0")"\n\nDYLD_LIBRARY_PATH=$HERE $HERE/main\n' > build/purpl-demo
          cp -r out/mac/{engine.dylib,main} deps/mac-x64/* deps/licenses build
          cp LICENSE build/licenses/purpl.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-macos
          path: build

      - name: Create zip of artifacts for release
        run: |
          7z a -tzip build-macos.zip build/*

      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-macos.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup APT packages
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.198-focal.list https://packages.lunarg.com/vulkan/1.2.198/lunarg-vulkan-1.2.198-focal.list
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib python3 curl
          sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev vulkan-sdk

      - name: Set permissions on executables
        run: |
          chmod a+x tools/deps.py
          chmod a+x tools/gn
          chmod a+x tools/ninja

      - name: Build dependencies
        run: tools/deps.py --verbose

      - name: Generate build files
        run: tools/gn gen out/linux
        
      - name: Build
        run: tools/ninja -C out/linux -j$[`nproc` + 2]

      - name: Add artifacts to folder
        run: |
          mkdir build
          printf '#!/usr/bin/env bash\n\nchmod a+x main\nexportHERE="$(dirname "$0")"\n\nLD_LIBRARY_PATH=$HERE $HERE/main\n' > build/purpl-demo
          cp -r out/linux/{engine.so,main} deps/linux-x64/* deps/licenses build
          cp LICENSE build/licenses/purpl.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-linux
          path: build

      - name: Create zip of artifacts for release
        run: |
          7z a -tzip build-linux.zip build/*

      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-linux.zip
